/** Cadenas mínimas para content scripts (ES/EN). */

/** @type {Record<'es' | 'en', Record<string, string>>} */
const STRINGS = {
  es: {
    'sfInject.debugLogOpenViewer.button': 'Abrir en SFOC',
    'sfInject.debugLogOpenViewer.ariaOpen': 'Abrir log de depuración en Salesforce Org Compare',
    'sfInject.debugLogOpenViewer.errorNoSession': 'Sesión no disponible. Inicia sesión en Salesforce.',
    'sfInject.debugLogOpenViewer.errorOpen': 'No se pudo abrir el log en SFOC.',
    'sfInject.debugLogOpenViewer.errorOrgNotSaved': 'Entorno no guardado en SFOC.',
    'sfInject.userTraceFlags.filterLabel':
      'Solo trazas activas o caducadas hace menos de 30 min',
    'sfInject.userTraceFlags.badgeExpired': 'Caducada',
    'sfInject.userTraceFlags.extend': 'Ampliar 15 min',
    'sfInject.userTraceFlags.reactivate': 'Reactivar 15 min',
    'sfInject.userTraceFlags.ariaExtend': 'Ampliar la traza 15 minutos',
    'sfInject.userTraceFlags.ariaReactivate': 'Reactivar la traza 15 minutos',
    'sfInject.userTraceFlags.extending': 'Ampliando traza…',
    'sfInject.userTraceFlags.extendOk': 'Traza ampliada 15 minutos.',
    'sfInject.userTraceFlags.reactivateOk': 'Traza reactivada 15 minutos.',
    'sfInject.userTraceFlags.extendError': 'No se pudo ampliar la traza.',
    'sfInject.userTraceFlags.extendMaxWindow': 'La traza ya alcanza el máximo de 24 horas.',
    'sfInject.userTraceFlags.errorNoSession': 'Sesión no disponible. Inicia sesión en Salesforce.',
    'sfInject.userTraceFlags.errorOrgNotSaved': 'Entorno no guardado en SFOC.',
    'sfInject.userTraceFlags.emptyFiltered': 'No hay trazas que cumplan el filtro.',
    'sfInject.deployStatus.toggleOpen': 'Mostrar detalles del despliegue fallido',
    'sfInject.deployStatus.toggleClose': 'Ocultar detalles del despliegue fallido',
    'sfInject.deployStatus.loading': 'Cargando detalles del despliegue…',
    'sfInject.deployStatus.retry': 'Reintentar',
    'sfInject.deployStatus.empty': 'Salesforce no devolvió detalles para este despliegue.',
    'sfInject.deployStatus.components': 'Fallos de componentes',
    'sfInject.deployStatus.tests': 'Fallos de tests',
    'sfInject.deployStatus.globalError': 'Error general',
    'sfInject.deployStatus.coverageWarnings': 'Avisos de cobertura',
    'sfInject.deployStatus.apiName': 'API Name',
    'sfInject.deployStatus.type': 'Type',
    'sfInject.deployStatus.line': 'Line',
    'sfInject.deployStatus.column': 'Column',
    'sfInject.deployStatus.errorMessage': 'Error Message',
    'sfInject.deployStatus.apexClass': 'Apex Class',
    'sfInject.deployStatus.testMethod': 'Test Method',
    'sfInject.deployStatus.stackTrace': 'Stack Trace',
    'sfInject.deployStatus.time': 'Time',
    'sfInject.deployStatus.openApex': 'Ctrl+clic para abrir en SFOC',
    'sfInject.deployStatus.errorNoSession': 'Sesión no disponible. Inicia sesión en Salesforce.',
    'sfInject.deployStatus.errorOrgNotSaved': 'Entorno no guardado en SFOC.',
    'sfInject.deployStatus.errorOpenApex': 'No se pudo abrir la clase Apex en SFOC.',
    'sfInject.deployStatus.errorLoad': 'No se pudieron cargar los detalles del despliegue.',
    'sfInject.deployDetailSource.orgLabel': 'Organización para abrir el código',
    'sfInject.deployDetailSource.noOrgs': 'No hay organizaciones conectadas',
    'sfInject.deployDetailSource.chooseOrg': 'Selecciona una organización',
    'sfInject.deployDetailSource.selectOrg': 'Selecciona una organización para abrir el código.',
    'sfInject.deployDetailSource.openHint': 'Ctrl/Cmd+clic para abrir en SFOC',
    'sfInject.deployDetailSource.noSession': 'La organización seleccionada no tiene una sesión activa.',
    'sfInject.deployDetailSource.orgNotSaved': 'La organización seleccionada ya no está guardada en SFOC.',
    'sfInject.deployDetailSource.classNotFound': 'La clase Apex no existe en la organización seleccionada.',
    'sfInject.deployDetailSource.openError': 'No se pudo abrir la clase Apex en SFOC.'
  },
  en: {
    'sfInject.debugLogOpenViewer.button': 'Open in SFOC',
    'sfInject.debugLogOpenViewer.ariaOpen': 'Open debug log in Salesforce Org Compare',
    'sfInject.debugLogOpenViewer.errorNoSession': 'Session unavailable. Sign in to Salesforce.',
    'sfInject.debugLogOpenViewer.errorOpen': 'Could not open log in SFOC.',
    'sfInject.debugLogOpenViewer.errorOrgNotSaved': 'Org not saved in SFOC.',
    'sfInject.userTraceFlags.filterLabel': 'Only active or expired within the last 30 min',
    'sfInject.userTraceFlags.badgeExpired': 'Expired',
    'sfInject.userTraceFlags.extend': 'Extend 15 min',
    'sfInject.userTraceFlags.reactivate': 'Reactivate 15 min',
    'sfInject.userTraceFlags.ariaExtend': 'Extend the trace by 15 minutes',
    'sfInject.userTraceFlags.ariaReactivate': 'Reactivate the trace for 15 minutes',
    'sfInject.userTraceFlags.extending': 'Extending trace…',
    'sfInject.userTraceFlags.extendOk': 'Trace extended by 15 minutes.',
    'sfInject.userTraceFlags.reactivateOk': 'Trace reactivated for 15 minutes.',
    'sfInject.userTraceFlags.extendError': 'Could not extend the trace.',
    'sfInject.userTraceFlags.extendMaxWindow': 'The trace already reaches the 24-hour maximum.',
    'sfInject.userTraceFlags.errorNoSession': 'Session unavailable. Sign in to Salesforce.',
    'sfInject.userTraceFlags.errorOrgNotSaved': 'Org not saved in SFOC.',
    'sfInject.userTraceFlags.emptyFiltered': 'No traces match the current filter.',
    'sfInject.deployStatus.toggleOpen': 'Show failed deployment details',
    'sfInject.deployStatus.toggleClose': 'Hide failed deployment details',
    'sfInject.deployStatus.loading': 'Loading deployment details…',
    'sfInject.deployStatus.retry': 'Retry',
    'sfInject.deployStatus.empty': 'Salesforce returned no details for this deployment.',
    'sfInject.deployStatus.components': 'Component failures',
    'sfInject.deployStatus.tests': 'Test failures',
    'sfInject.deployStatus.globalError': 'General error',
    'sfInject.deployStatus.coverageWarnings': 'Coverage warnings',
    'sfInject.deployStatus.apiName': 'API Name',
    'sfInject.deployStatus.type': 'Type',
    'sfInject.deployStatus.line': 'Line',
    'sfInject.deployStatus.column': 'Column',
    'sfInject.deployStatus.errorMessage': 'Error Message',
    'sfInject.deployStatus.apexClass': 'Apex Class',
    'sfInject.deployStatus.testMethod': 'Test Method',
    'sfInject.deployStatus.stackTrace': 'Stack Trace',
    'sfInject.deployStatus.time': 'Time',
    'sfInject.deployStatus.openApex': 'Ctrl+click to open in SFOC',
    'sfInject.deployStatus.errorNoSession': 'Session unavailable. Sign in to Salesforce.',
    'sfInject.deployStatus.errorOrgNotSaved': 'Org not saved in SFOC.',
    'sfInject.deployStatus.errorOpenApex': 'Could not open the Apex class in SFOC.',
    'sfInject.deployStatus.errorLoad': 'Could not load deployment details.',
    'sfInject.deployDetailSource.orgLabel': 'Org used to open source',
    'sfInject.deployDetailSource.noOrgs': 'No connected organizations',
    'sfInject.deployDetailSource.chooseOrg': 'Select an organization',
    'sfInject.deployDetailSource.selectOrg': 'Select an organization to open source.',
    'sfInject.deployDetailSource.openHint': 'Ctrl/Cmd+click to open in SFOC',
    'sfInject.deployDetailSource.noSession': 'The selected organization has no active session.',
    'sfInject.deployDetailSource.orgNotSaved': 'The selected organization is no longer saved in SFOC.',
    'sfInject.deployDetailSource.classNotFound': 'The Apex class does not exist in the selected organization.',
    'sfInject.deployDetailSource.openError': 'Could not open the Apex class in SFOC.'
  }
};

/** @param {'es' | 'en' | string | undefined} lang @param {string} key */
export function sfInjectT(lang, key) {
  const l = lang === 'en' ? 'en' : 'es';
  return STRINGS[l][key] || STRINGS.es[key] || key;
}
